### ISSUE TITLE
oωo-lib Conflict Prevents Stacking in Furnaces

### ISSUE THREAD

**Issue by BlindTwig** [boyonk913/item-components#2]
With the mod installed, smelting stacks of items in any type of furnace no longer works correctly. It will smelt the first item, and then not continue until that item is taken out, making it possible to unknowingly waste a lot of fuel, and making it much more tedious to smelt items. This behavior immediately stopped upon disabling the mod, and all furnaces functioned normally again.

**Comment by boyonk913** [comment]
Hi!

I am unable to recreate this issue. Could you share more information on how to reproduce it?
- What other mods are you using?
- Which version of Minecraft are you on?
- Does the issue happen when only using Fabric API & Item Components?

**Comment by BlindTwig** [comment]
I'm on Minecraft 1.21, Fabric Loader version 0.16.5 and API version 0.102.0. I have done further testing since my original report, and it doesn't happen with just the API and Item Components. Unfortunately my modlist is quite large, so to not inconvenience you, I'm going to attempt to find exactly which mod is conflicting and causing the issue instead of dumping my massive list of mods onto you, I'll get back to you when I've found it.

**Comment by BlindTwig** [comment]
It's taking me a lot longer than I expected, I'm going to keep going at it but in case I don't find the cause tonight, I'll leave my modlist in case you want to sift through what mods could be causing it.
[modlist.txt](https://github.com/user-attachments/files/17105897/modlist.txt)

**Comment by xnite7** [comment]
hey i have a quite similar modlist and im also experiencing this issue with items not stacking in a furnace, have u found the mod thats causing this by any chance?

**Comment by BlindTwig** [comment]
I have not yet found it, no, I had to stop searching last night due to a migraine from having worked all day, but I hope to continue looking sometime today. If you can you should try to find it as well, more people with the issue looking for the cause would make this much faster to find.

**Comment by maevius669** [comment]
try disabling [oωo](https://modrinth.com/mod/ccKDOlHs)

aside from this issue, it needs `/reload` everytime I load a new world after starting minecraft,
but it doesnt need it when you exit a world and rejoin.
