### ISSUE TITLE
Stack Size Component Isn't Applied Until Reload

### ISSUE THREAD

**Issue by Noobulus** [boyonk913/item-components#5]
After loading a world with this mod installed on 1.21.1 and a component file in the correct place, the stack size change I made to potions doesn't apply.
![Screenshot_20241024_113144](https://github.com/user-attachments/assets/daec500f-9a4e-4b33-8982-1ad2565ec077)

...That is, until I `/reload` and it applies just fine.
![Screenshot_20241024_113156](https://github.com/user-attachments/assets/1dbb1079-1855-4033-a323-822a3ad8e132)

My components file is as follows:
```
{
  "targets": "#c:potions",
  "components": {
    "minecraft:max_stack_size": 16
  }
}
```

**Comment by alexmozaidze** [comment]
Same issue. This might be ok on multiplayer, since you can setup automatic `/reload` on a server reboot, but in singleplayer it's very annoying. I have to open for LAN with cheats in order to `/reload`.
